{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e9bf862-6e82-4882-b29d-5f5808e23697",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python\n",
    "\n",
    "# ==============================\n",
    "# Import librerie\n",
    "# ==============================\n",
    "\n",
    "# pandas serve per creare il dataframe Excel\n",
    "import pandas as pd\n",
    "\n",
    "# pathlib serve per lavorare con file e cartelle\n",
    "from pathlib import Path\n",
    "\n",
    "# re serve per leggere il numero dei chunk dal nome file\n",
    "import re\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Header\n",
    "# ==============================\n",
    "\n",
    "print(\"\\n==============================\")\n",
    "print(\"Build Chunk Excel\")\n",
    "print(\"==============================\\n\")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Input utente\n",
    "# ==============================\n",
    "\n",
    "# Chiede la directory base degli spettrogrammi\n",
    "# esempio: /Volumes/FC2280/fc2280\n",
    "base_dir = input(\"Spectrogram base directory: \").strip('\"')\n",
    "\n",
    "# Chiede l'anno da processare\n",
    "# esempio: 2023\n",
    "year = input(\"Year (e.g. 2023): \")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Costruzione path base\n",
    "# ==============================\n",
    "\n",
    "# Costruisce il path:\n",
    "# /Volumes/FC2280/fc2280/2023\n",
    "base_path = Path(base_dir) / year\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Livelli spettrogrammi\n",
    "# ==============================\n",
    "\n",
    "# Le cartelle create da generate_spectrograms.py\n",
    "levels = [\"LOW\", \"MEDIUM\", \"HIGH\"]\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Lista righe excel\n",
    "# ==============================\n",
    "\n",
    "# Lista vuota dove verranno salvate le righe Excel\n",
    "rows = []\n",
    "\n",
    "\n",
    "print(\"\\nScanning folders...\\n\")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Loop sui livelli\n",
    "# ==============================\n",
    "\n",
    "for level in levels:\n",
    "\n",
    "    # Costruisce path livello\n",
    "    # esempio: /2023/LOW\n",
    "    level_path = base_path / level\n",
    "\n",
    "    # Se la cartella non esiste la salta\n",
    "    if not level_path.exists():\n",
    "        print(f\"Skipping {level}\")\n",
    "        continue\n",
    "\n",
    "    # ==============================\n",
    "    # Loop recording\n",
    "    # ==============================\n",
    "\n",
    "    # Trova tutte le cartelle recording\n",
    "    recordings = sorted(\n",
    "        [d for d in level_path.iterdir() if d.is_dir()]\n",
    "    )\n",
    "\n",
    "    # Loop sulle recordings\n",
    "    for rec in recordings:\n",
    "\n",
    "        # Trova tutti i chunk PNG\n",
    "        chunks = sorted(rec.glob(\"*.png\"))\n",
    "\n",
    "        # Loop sui chunk\n",
    "        for chunk in chunks:\n",
    "\n",
    "            # ==============================\n",
    "            # Estrazione chunk id\n",
    "            # ==============================\n",
    "\n",
    "            # Cerca \"chunk_XX\" nel nome file\n",
    "            match = re.search(r\"chunk_(\\d+)\", chunk.name)\n",
    "\n",
    "            if match:\n",
    "                chunk_id = int(match.group(1))\n",
    "            else:\n",
    "                chunk_id = None\n",
    "\n",
    "\n",
    "            # ==============================\n",
    "            # Parsing datetime\n",
    "            # ==============================\n",
    "\n",
    "            datetime_str = None\n",
    "            year_val = None\n",
    "            month = None\n",
    "            day = None\n",
    "            hour = None\n",
    "            sec = None\n",
    "\n",
    "            try:\n",
    "\n",
    "                # Nome recording esempio:\n",
    "                # REC_20140429_230000\n",
    "                parts = rec.name.split(\"_\")\n",
    "\n",
    "                # Estrazione anno mese giorno\n",
    "                year_val = parts[1][:4]\n",
    "                month = parts[1][4:6]\n",
    "                day = parts[1][6:8]\n",
    "\n",
    "                # Estrazione ora secondi\n",
    "                hour = parts[2][:2]\n",
    "                sec = parts[2][2:4]\n",
    "\n",
    "                # Costruzione datetime string\n",
    "                datetime_str = f\"{year_val}-{month}-{day}_{hour}:{sec}\"\n",
    "\n",
    "            except:\n",
    "                # Se parsing fallisce lascia vuoto\n",
    "                pass\n",
    "\n",
    "\n",
    "            # ==============================\n",
    "            # Creazione riga Excel\n",
    "            # ==============================\n",
    "\n",
    "            row = {\n",
    "\n",
    "                # Info temporali\n",
    "                \"datetime_str\": datetime_str,\n",
    "                \"year\": year_val,\n",
    "                \"month\": month,\n",
    "                \"day\": day,\n",
    "                \"hour\": hour,\n",
    "                \"sec\": sec,\n",
    "\n",
    "                # Info recording\n",
    "                \"file_name\": rec.name + \".wav\",\n",
    "                \"recording\": rec.name,\n",
    "\n",
    "                # Info chunk\n",
    "                \"chunk_id\": chunk_id,\n",
    "                \"chunk_file\": chunk.name,\n",
    "\n",
    "                # Livello classificazione\n",
    "                \"level\": level,\n",
    "\n",
    "                # Info durata\n",
    "                \"duration_sec\": \"\",\n",
    "\n",
    "                # Verifica Raven\n",
    "                \"raven_checked\": \"\",\n",
    "\n",
    "                # Annotazioni chunk\n",
    "                \"chunk_presence\": \"\",\n",
    "                \"chunk_sound_type\": \"\",\n",
    "                \"chunk_confidence\": \"\",\n",
    "                \"chunk_notes\": \"\"\n",
    "\n",
    "            }\n",
    "\n",
    "            # Aggiunge riga alla lista\n",
    "            rows.append(row)\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Output numero chunk\n",
    "# ==============================\n",
    "\n",
    "print(f\"\\nTotal chunks found: {len(rows)}\")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Creazione dataframe\n",
    "# ==============================\n",
    "\n",
    "df = pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Sorting\n",
    "# ==============================\n",
    "\n",
    "# Ordina per recording livello chunk\n",
    "df = df.sort_values(\n",
    "    [\"recording\", \"level\", \"chunk_id\"]\n",
    ")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Output file\n",
    "# ==============================\n",
    "\n",
    "output = f\"beluga_chunks_{year}.xlsx\"\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Salvataggio Excel\n",
    "# ==============================\n",
    "\n",
    "df.to_excel(output, index=False)\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Fine\n",
    "# ==============================\n",
    "\n",
    "print(f\"\\nSaved: {output}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (edansa_env)",
   "language": "python",
   "name": "edansa_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
