{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9a0a4362-2019-463d-82d6-0dd2e5729d1a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python\n",
    "\n",
    "# ==============================\n",
    "# Import librerie\n",
    "# ==============================\n",
    "\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Header\n",
    "# ==============================\n",
    "\n",
    "print(\"\\n==============================\")\n",
    "print(\"Merge Chunk Excel Files\")\n",
    "print(\"==============================\\n\")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Input utente\n",
    "# ==============================\n",
    "\n",
    "# directory contenente excel annotati\n",
    "input_dir = input(\n",
    "    \"Directory with annotation Excel files: \"\n",
    ").strip('\"')\n",
    "\n",
    "# directory output\n",
    "output_dir = input(\n",
    "    \"Output directory: \"\n",
    ").strip('\"')\n",
    "\n",
    "# nome file output\n",
    "output_name = input(\n",
    "    \"Output file name (e.g. beluga_merged.xlsx): \"\n",
    ")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Costruzione path\n",
    "# ==============================\n",
    "\n",
    "input_path = Path(input_dir)\n",
    "output_path = Path(output_dir)\n",
    "\n",
    "\n",
    "# crea directory output se non esiste\n",
    "output_path.mkdir(\n",
    "    parents=True,\n",
    "    exist_ok=True\n",
    ")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Trova file Excel\n",
    "# ==============================\n",
    "\n",
    "excel_files = sorted(\n",
    "    input_path.glob(\"*.xlsx\")\n",
    ")\n",
    "\n",
    "print(\n",
    "    f\"\\nFound {len(excel_files)} Excel files\"\n",
    ")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Lista dataframe\n",
    "# ==============================\n",
    "\n",
    "dfs = []\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Loop file\n",
    "# ==============================\n",
    "\n",
    "for file in excel_files:\n",
    "\n",
    "    print(f\"Loading: {file.name}\")\n",
    "\n",
    "    df = pd.read_excel(file)\n",
    "\n",
    "    dfs.append(df)\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Merge dataframe\n",
    "# ==============================\n",
    "\n",
    "merged_df = pd.concat(\n",
    "    dfs,\n",
    "    ignore_index=True\n",
    ")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Sorting finale\n",
    "# ==============================\n",
    "\n",
    "merged_df = merged_df.sort_values(\n",
    "    [\"year\", \"recording\", \"level\", \"chunk_id\"]\n",
    ")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Salvataggio\n",
    "# ==============================\n",
    "\n",
    "final_output = output_path / output_name\n",
    "\n",
    "merged_df.to_excel(\n",
    "    final_output,\n",
    "    index=False\n",
    ")\n",
    "\n",
    "\n",
    "# ==============================\n",
    "# Fine\n",
    "# ==============================\n",
    "\n",
    "print(\"\\nMerge completed\")\n",
    "print(f\"Saved: {final_output}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (edansa_env)",
   "language": "python",
   "name": "edansa_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
